### ISSUE TITLE
Ogg intead of wav? [optimization] [question]

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/animal-farm#2]
Do you think interesting / useful if I compress wav files to ogg. That would make app smaller specially if more animals are added

**Comment by bhdouglass** [comment]
I don't have a problem doing that 👍

**Comment by cibersheep** [comment]
Oh :( 
http://doc.qt.io/qt-5/qsoundeffect.html
![imatge](https://user-images.githubusercontent.com/6640041/34400970-323ac642-eb97-11e7-9bed-37870e6420af.png)

Well, I'll do a test tomorrow with: https://docs.ubuntu.com/phone/en/apps/api-qml-development/QtMultimedia.MediaPlayer
Let's see

**Comment by bhdouglass** [comment]
MediaPlayer worked and we now have oggs in v6.1.0!
